jobs:
  tests:
    permissions:
      contents: 'write'
    runs-on: '${{ matrix.backend.runner }}'
    steps:
      - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1'
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: 'actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1'
        with:
          python-version: '3.13'
      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov libcmocka-dev ninja-build pkg-config
          python -m pip install --upgrade meson
      - name: 'Configure'
        run: >-
          meson setup build --buildtype '${{ matrix.build-type }}'
          -Db_coverage=true -Dtests=enabled
          ${{ matrix.backend.force_generic && '-Dforce_generic=true' || '' }}
      - name: 'Build'
        run: 'meson compile -C build --verbose'
      - name: 'Run tests'
        run: 'meson test -C build --print-errorlogs'
      - if: "matrix.build-type == 'debug'"
        name: 'Generate coverage information'
        run: >-
          lcov -c -d build -o coverage.lcov
          --exclude build
          --exclude tests
          --exclude '*/subprojects/*'
          --include '*/native/*'
          --keep-going
      - if: "matrix.build-type == 'debug'"
        name: 'Coveralls'
        uses: 'coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e'
        with:
          file: 'coverage.lcov'
          flag-name: '${{ matrix.backend.suffix }}-${{ matrix.build-type }}'
          parallel: true
    strategy:
      fail-fast: false
      matrix:
        backend:
          - force_generic: false
            runner: 'ubuntu-latest'
            suffix: 'x86_64'
          - force_generic: false
            runner: 'ubuntu-24.04-arm'
            suffix: 'aarch64'
          - force_generic: true
            runner: 'ubuntu-latest'
            suffix: 'generic'
        build-type: ['debug', 'release']
  finish-coveralls:
    needs: 'tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Finalise Coveralls report'
        uses: 'coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e'
        with:
          parallel-finished: true
name: 'Native Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
